import type { components } from './generated/schema'

export type AccessTokenResponse = components['schemas']['AccessTokenResponse']
export type PublicUser = components['schemas']['PublicUser']
export type UserRegistrationRequest = components['schemas']['UserRegistrationRequest']
export type ActivityLevel = components['schemas']['ActivityLevel']
export type NutritionGoal = components['schemas']['NutritionGoal']
export type NutritionProfileResponse = components['schemas']['NutritionProfileResponse']
export type NutritionProfileUpdateRequest = components['schemas']['NutritionProfileUpdateRequest']
export type NutritionTargetResponse = components['schemas']['NutritionTargetResponse']
export type NutritionTargetUpdateRequest = components['schemas']['NutritionTargetUpdateRequest']
export type TargetSourceType = components['schemas']['TargetSourceType']
export type DailyProgressResponse = components['schemas']['DailyProgressResponse']
export type TargetStatusResponse = components['schemas']['TargetStatusResponse']
export type MealListResponse = components['schemas']['MealListResponse']
export type MealResponse = components['schemas']['MealResponse']
export type NutrientTotals = components['schemas']['NutrientTotals']
export type WeeklyProgressResponse = components['schemas']['WeeklyProgressResponse']
export type ProgressSummaryResponse = components['schemas']['ProgressSummaryResponse']
export type DailyProgressPoint = components['schemas']['DailyProgressPoint']
export type MealCreateRequest = components['schemas']['MealCreateRequest']
export type MealAnalysisResponse = components['schemas']['CalculatedMealAnalysis'] | components['schemas']['FoodNotRecognizedMealAnalysis'] | components['schemas']['NutritionReferenceNotFoundMealAnalysis'] | components['schemas']['RequiresFoodSelectionMealAnalysis']
export type NutritionCoachRequest = components['schemas']['NutritionCoachRequest']
export type NutritionCoachResponse = components['schemas']['NutritionCoachResponse']
