import type { components } from './generated/schema'

export type AccessTokenResponse = components['schemas']['AccessTokenResponse']
export type PublicUser = components['schemas']['PublicUser']
export type UserRegistrationRequest = components['schemas']['UserRegistrationRequest']
export type ActivityLevel = components['schemas']['ActivityLevel']
export type NutritionGoal = components['schemas']['NutritionGoal']
export type NutritionProfileResponse = components['schemas']['NutritionProfileResponse']
export type NutritionProfileUpdateRequest = components['schemas']['NutritionProfileUpdateRequest']
export type NutritionTargetResponse = components['schemas']['NutritionTargetResponse']
export type NutritionTargetUpdateRequest = components['schemas']['NutritionTargetUpdateRequest']
export type TargetSourceType = components['schemas']['TargetSourceType']
export type DailyProgressResponse = components['schemas']['DailyProgressResponse']
export type TargetStatusResponse = components['schemas']['TargetStatusResponse']
export type MealListResponse = components['schemas']['MealListResponse']
export type NutrientTotals = components['schemas']['NutrientTotals']
