"""create meals and meal items

Revision ID: 13a13029351a
Revises: 72c641c22b2d
Create Date: 2026-08-10 22:42:42.053395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a13029351a'
down_revision: Union[str, Sequence[str], None] = '72c641c22b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_calories', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('total_protein_g', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('total_carbohydrates_g', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('total_fat_g', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('total_fiber_g', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_recorded_at'), 'meals', ['recorded_at'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('weight_grams', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('calculated_calories', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('calculated_protein_g', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('calculated_carbohydrates_g', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('calculated_fat_g', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('calculated_fiber_g', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('food_name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('food_normalized_name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('calculated_calories >= 0', name='ck_meal_items_calories_nonnegative'),
    sa.CheckConstraint('calculated_carbohydrates_g >= 0', name='ck_meal_items_carbohydrates_nonnegative'),
    sa.CheckConstraint('calculated_fat_g >= 0', name='ck_meal_items_fat_nonnegative'),
    sa.CheckConstraint('calculated_fiber_g >= 0', name='ck_meal_items_fiber_nonnegative'),
    sa.CheckConstraint('calculated_protein_g >= 0', name='ck_meal_items_protein_nonnegative'),
    sa.CheckConstraint('weight_grams <= 5000', name='ck_meal_items_weight_maximum'),
    sa.CheckConstraint('weight_grams > 0', name='ck_meal_items_weight_positive'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_items_food_id'), 'meal_items', ['food_id'], unique=False)
    op.create_index(op.f('ix_meal_items_meal_id'), 'meal_items', ['meal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_items_meal_id'), table_name='meal_items')
    op.drop_index(op.f('ix_meal_items_food_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_meals_recorded_at'), table_name='meals')
    op.drop_table('meals')
    # ### end Alembic commands ###
