"""create nutrition targets

Revision ID: 6b4e2f24290a
Revises: db14ea469341
Create Date: 2026-08-11 10:27:40.790104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4e2f24290a'
down_revision: Union[str, Sequence[str], None] = 'db14ea469341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('carbohydrates_g', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('manual', 'researcher_assigned', 'professional_assigned')", name='ck_targets_source_type'),
    sa.CheckConstraint('calories IS NULL OR calories > 0 AND calories <= 100000', name='ck_targets_calories_range'),
    sa.CheckConstraint('carbohydrates_g IS NULL OR carbohydrates_g > 0 AND carbohydrates_g <= 10000', name='ck_targets_carbohydrates_range'),
    sa.CheckConstraint('fat_g IS NULL OR fat_g > 0 AND fat_g <= 10000', name='ck_targets_fat_range'),
    sa.CheckConstraint('fiber_g IS NULL OR fiber_g > 0 AND fiber_g <= 10000', name='ck_targets_fiber_range'),
    sa.CheckConstraint('protein_g IS NULL OR protein_g > 0 AND protein_g <= 10000', name='ck_targets_protein_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_targets_user_id'), 'nutrition_targets', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrition_targets_user_id'), table_name='nutrition_targets')
    op.drop_table('nutrition_targets')
    # ### end Alembic commands ###
