"""create foods table

Revision ID: 72c641c22b2d
Revises: 
Create Date: 2026-08-10 15:29:17.966673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c641c22b2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('calories_per_100g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('protein_g_per_100g', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('carbohydrates_g_per_100g', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('fat_g_per_100g', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('fiber_g_per_100g', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('source_name', sa.String(length=160), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('calories_per_100g >= 0', name='ck_foods_calories_nonnegative'),
    sa.CheckConstraint('carbohydrates_g_per_100g >= 0', name='ck_foods_carbohydrates_nonnegative'),
    sa.CheckConstraint('fat_g_per_100g >= 0', name='ck_foods_fat_nonnegative'),
    sa.CheckConstraint('fiber_g_per_100g >= 0', name='ck_foods_fiber_nonnegative'),
    sa.CheckConstraint('protein_g_per_100g >= 0', name='ck_foods_protein_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
