"""create users profiles and meal ownership

Revision ID: 9a4a4d50752e
Revises: 13a13029351a
Create Date: 2026-08-10 23:08:09.049895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9a4a4d50752e'
down_revision: Union[str, Sequence[str], None] = '13a13029351a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('nutrition_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('activity_level', sa.String(length=32), nullable=True),
    sa.Column('nutrition_goal', sa.String(length=32), nullable=True),
    sa.Column('dietary_restrictions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("activity_level IS NULL OR activity_level IN ('sedentary', 'lightly_active', 'moderately_active', 'very_active')", name='ck_profiles_activity_level'),
    sa.CheckConstraint("jsonb_typeof(allergies) = 'array'", name='ck_profiles_allergies_array'),
    sa.CheckConstraint("jsonb_typeof(dietary_restrictions) = 'array'", name='ck_profiles_dietary_restrictions_array'),
    sa.CheckConstraint("nutrition_goal IS NULL OR nutrition_goal IN ('maintain_weight', 'lose_weight', 'gain_weight', 'general_health')", name='ck_profiles_nutrition_goal'),
    sa.CheckConstraint('age IS NULL OR age BETWEEN 0 AND 130', name='ck_profiles_age_range'),
    sa.CheckConstraint('height_cm IS NULL OR height_cm > 0 AND height_cm <= 300', name='ck_profiles_height_range'),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg > 0 AND weight_kg <= 500', name='ck_profiles_weight_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_profiles_user_id'), 'nutrition_profiles', ['user_id'], unique=True)
    op.add_column('meals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_foreign_key('fk_meals_user_id_users', 'meals', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_meals_user_id_users', 'meals', type_='foreignkey')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_column('meals', 'user_id')
    op.drop_index(op.f('ix_nutrition_profiles_user_id'), table_name='nutrition_profiles')
    op.drop_table('nutrition_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
