"""add meals progress query index

Revision ID: db14ea469341
Revises: 9a4a4d50752e
Create Date: 2026-08-10 23:55:18.607039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db14ea469341'
down_revision: Union[str, Sequence[str], None] = '9a4a4d50752e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_meals_user_id_recorded_at', 'meals', ['user_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meals_user_id_recorded_at', table_name='meals')
    # ### end Alembic commands ###
